### ISSUE TITLE
maintenance status

### ISSUE THREAD

**Issue by dougwilson** [visionmedia/connect-render#10]
Hi @fengmk2 👋 and other repo owners,

I'm wondering who the current maintainer of this repo is as a point of contact for changes.

**Comment by fengmk2** [comment]
@dougwilson  I'm **not** using express and connect for a long time. 
I can help to fix the security issue this time, but need to find a new maintainer for this repo in the future.

**Comment by dougwilson** [comment]
Hi @fengmk2 you don't even need to change anything at this time :) I was just asking to know. It is 100% OK if you don't want to continue to maintain it :) We can mark it deprecated until someone else wants to come along, of course.

**Comment by fengmk2** [comment]
@dougwilson Yep, mark it deprecated please.

**Comment by dougwilson** [comment]
👍

**Comment by fengmk2** [comment]
I have deprecated it on the npm just now.

```
deprecated: 'Please use express template engines instead, see https://expressjs.com/en/guide/using-template-engines.html'
```

**Comment by dougwilson** [comment]
I also moved the repo over to `visionmedia` org (and invited you if you want), which helps place it in the kinda "old TJ modules that need love" zone :)
